# Generated by Django 2.2.4 on 2019-11-09 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Running',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('progress', models.DecimalField(decimal_places=1, max_digits=3)),
                ('errors', models.IntegerField()),
                ('time_started', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
