# Generated by Django 2.2.4 on 2019-11-11 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eplus_main', '0002_auto_20191109_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
