# Generated by Django 2.2.4 on 2019-11-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eplus_main', '0004_auto_20191111_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='progress',
        ),
        migrations.AddField(
            model_name='process',
            name='current_file',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='process',
            name='total_files',
            field=models.IntegerField(default=0),
        ),
    ]
